version: '3.7'
services:
  web:
    build: docker/apache
    container_name: ${PROJECT_NAME}_web
    volumes:
     # les fichiers du site seront à placer dans le dossier web suivi du nom du projet
     - ./web_${PROJECT_NAME}:${PROJECT_PATH}:cached
     - ./docker/apache/sites_enabled:/etc/apache2/sites_enabled
     - ./docker/php/custom-php.ini:/use/local/etc/php/conf.d/custom-php.ini
    depends_on:
     - db
    ports:
     - "8082:80"
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      UPLOAD_LIMIT: 20M
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db_data:/var/lib/mysql      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    depends_on:
     - db
    ports:
     - "8083:80"
    environment:
     - PMA_HOST=db
     - UPLOAD_LIMIT="20M"
volumes:
  db_data:

